apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airflow-rabbitmq
  name: airflow-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-rabbitmq
  template:
    metadata:
      labels:
        app: airflow-rabbitmq
    spec:
      containers:
      - image: airflow-rabbitmq:0.1
        name: airflow-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-rabbitmq
spec:
  ports:
  - name: tcp-amqp
    port: 5672
    targetPort: 5672
  - name: http-management
    port: 15672
    targetPort: 15672
  selector:
    app: airflow-rabbitmq
