apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airflow-flower
  name: airflow-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-flower
  template:
    metadata:
      labels:
        app: airflow-flower
    spec:
      containers:
      - image: airflow-slim:0.1
        name: airflow-flower
        args:
        - "flower"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: CLUSTER_NAME
          value: "airflow-worker"
        - name: CELERY_WORKER_CONCURRENCY
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-flower
spec:
  type: NodePort
  ports:
    - name: flower-api
      port: 5555
      targetPort: 5555
      nodePort: 31000
    - name: shutdown-api
      port: 5559
      targetPort: 5559
  selector:
    app: airflow-flower
