apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airflow-scheduler
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - image: airflow-slim:0.1
        name: airflow-scheduler
        args:
        - "scheduler"
        - "initialize"
        volumeMounts:
        - mountPath: /home/airflow/dags
          name: airflowdags
        - mountPath: /home/airflow/logs
          name: airflowlogs          
      volumes:
      - name: airflowdags
        hostPath:
          path: /home/docker/dags
      - name: airflowlogs
        hostPath:
          path: /home/docker/logs
